name: build

env:
  CONAN_REFERENCE: "nodejs/14.17.3"
  CONAN_USERNAME: "conan-burrito"
  CONAN_STABLE_BRANCH_PATTERN: "release/*"
  CONAN_UPLOAD: "${{ secrets.CONAN_UPLOAD }}"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout profiles
        uses: actions/checkout@v2
        with:
          repository: conan-burrito/profiles
          path: profiles
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan conan_package_tools
            conan remote disable conancenter
      - name: Build native
        run:  |
          python .ci/build-default.py
